server:
  port: 8083
  tomcat:
    max-http-form-post-size: 20MB

spring:
  application:
    name: music
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/music?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 147236
    tomcat:
      initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  redis:
    host: 120.25.161.31
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
      shutdown-timeout: 100
#    connect-timeout: 50000ms
    password: 159753
  rabbitmq:
    host: 120.25.161.31
    port: 5672
    username: root
    password: 147236
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
          max-interval: 15000
          multiplier: 2
        acknowledge-mode: manual
#logging:
#  level:
#    com.cumt: debug
mybatis-plus:
  mapper-locations: classpath:mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl