server:
  port: 8081
  tomcat:
    max-http-form-post-size: 20MB

spring:
  application:
    name: music
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/musicPay?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: xxxx
    tomcat:
      initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  redis:
    host: xxx
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
#      shutdown-timeout: 1000
    password: xxxx
  rabbitmq:
    host: xxx
    port: 5672
    username: root
    password: xxxx
    virtual-host: /
#logging:
#  level:
#    com.cumt: debug
mybatis-plus:
  mapper-locations: classpath:mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


